### ISSUE TITLE
collection object protected getter into TypedCollection?

### ISSUE THREAD

**Issue by bcolucci** [yvoyer/collection#15]
Hi,
Is it possible to add a protected getter of the "collection" attribute from the TypedCollection class? It'll be helpfull ;)
In fact, I can get a same object this way (if my class extends TypedCollection):
$collection = new ArrayCollection($this->getValues());

**Comment by yvoyer** [comment]
I don't want to expose information about the behavior of the class outside of it. If you need the elements of the collection, you can use `$collection->toArray();`. 

@bcolucci Does this represent your Use case?

```
YourOwnCollection extends TypedCollection
{
    public function someAction() 
    {
          $collection = new ArrayCollection($this->protectedGetter())
    }
}
```

**Comment by bcolucci** [comment]
Yes, I've made a private function for it (I need it only in private scope):
`private function getCollection() { return new ArrayCollection($this->getValues()); }`

**Comment by yvoyer** [comment]
There is already a method for this use case. As I said, if you want the elements of the collection:

```
YourOwnCollection extends TypedCollection
{
    public function __construct(array $values)
    {
        parent::__construct('YourOwnClass', $values);
    }

    public function someAction() 
    {
          $collection = new self($this->toArray())
    }
}
```

But I don't recommend this usage, since now a lot of your code could know about all the methods of `TypedCollection` (throught inheritance), instead of just knowing specific methods relevant to your logic on the wrapped object. (see my `CarCollection` example in the test folder.
